### ISSUE TITLE
GT failing in mockserver

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#1004]
when running `update_state.py all`:

```
Traceback (most recent call last):
  File "mockserver/update_state.py", line 70, in <module>
    mod = importlib.import_module('parsers.%s' % mod_name)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/oliviercorradi/github/tmrow/electricitymap/parsers/GT.py", line 15
SyntaxError: Non-ASCII character '\xc3' in file /Users/oliviercorradi/github/tmrow/electricitymap/parsers/GT.py on line 15, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

same with MD, PE and PA

**Comment by systemcatch** [comment]
It looks like python 2.7 is being run? That will give unicode errors.

**Comment by corradio** [comment]
ha! you're right!
