### ISSUE TITLE
MISO has a json decoding error

### ISSUE THREAD

**Issue by systemcatch** [tmrowco/electricitymap#1149]
Seems like MISO has been down for at least 24 hours. When I run it manually I get the following error.
```
(EM-env) chris@ThinkPad:~/electricitymap/parsers$ python US_MISO.py 
fetch_production() ->
Traceback (most recent call last):
  File "US_MISO.py", line 124, in <module>
    print(fetch_production())
  File "US_MISO.py", line 108, in fetch_production
    json_data = get_json_data(session = None)
  File "US_MISO.py", line 30, in get_json_data
    json_data = s.get(mix_url).json()
  File "/home/chris/EM-env/lib/python3.5/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by systemcatch** [comment]
The error is caused by https://github.com/tmrowco/electricitymap/blob/master/parsers/US_MISO.py#L10. At the end of the mix_url a space was added, annoyingly the API fails silently rather than returning a decent error message.

PEP8 refactoring in https://github.com/tmrowco/electricitymap/commit/8861f5b5d6a62aefcd662df61c82bc6cc38262aa caused this. Submitting a fix.
