### ISSUE TITLE
Error when building from Dockerfile

### ISSUE THREAD

**Issue by karim7878** [tmrowco/electricitymap#1167]
I have an error during the build Dockerfile.
```
Successfully built 6b5640ec7bbe
Creating electricitymap_mockserver_1 ... done
Creating electricitymap_mockserver_1 ...
Creating electricitymap_web_1        ... done
Attaching to electricitymap_mockserver_1, electricitymap_web_1
web_1         | npm info it worked if it ends with ok
web_1         | npm info using npm@5.3.0
web_1         | npm info using node@v8.5.0
web_1         | npm info lifecycle electricitymap-api@0.0.1~preserver-dev: electricitymap-api@0.0.1
web_1         | npm info lifecycle electricitymap-api@0.0.1~server-dev: electricitymap-api@0.0.1
web_1         |
web_1         | > electricitymap-api@0.0.1 server-dev /home/web
web_1         | > nodemon server.js
web_1         |
web_1         | [nodemon] 1.12.1
web_1         | [nodemon] to restart at any time, enter `rs`
web_1         | [nodemon] watching: *.*
web_1         | [nodemon] starting `node server.js`
web_1         | fs.js:653
web_1         |   return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
web_1         |                  ^
web_1         |
web_1         | Error: ENOENT: no such file or directory, open '/home/web/public/dist/manifest.json'
web_1         |     at Object.fs.openSync (fs.js:653:18)
web_1         |     at Object.fs.readFileSync (fs.js:554:33)
web_1         |     at Object.<anonymous> (/home/web/server.js:111:27)
web_1         |     at Module._compile (module.js:624:30)
web_1         |     at Object.Module._extensions..js (module.js:635:10)
web_1         |     at Module.load (module.js:545:32)
web_1         |     at tryModuleLoad (module.js:508:12)
web_1         |     at Function.Module._load (module.js:500:3)
web_1         |     at Function.Module.runMain (module.js:665:10)
web_1         |     at startup (bootstrap_node.js:201:16)
web_1         | [nodemon] app crashed - waiting for file changes before starting...
```

**Comment by corradio** [comment]
You need to run `docker-compose run --rm web npm run watch` alongside in order to watch/recompile (which will generate the manifest).

see https://github.com/tmrowco/electricitymap#running-locally

**Comment by karim7878** [comment]
Not working maybe your contenainet are an errot during copy manifest

Envoyé de mon iPhone

**Comment by corradio** [comment]
Join us on slack on #electricitymap and then we'll figure it out together

**Comment by karim7878** [comment]
Whats url link please 

Envoyé de mon iPhone

**Comment by corradio** [comment]
slack.tmrow.co
