### ISSUE TITLE
No data is shown for Balearic and Canary Islands

### ISSUE THREAD

**Issue by alixunderplatz** [tmrowco/electricitymap#1420]
Seems like something hasn't been working properly since yesterday after ~13:30 MEST

![image](https://user-images.githubusercontent.com/25743609/40266453-a0f79122-5b4b-11e8-8d33-3e4ced95ae12.png)

**Comment by kikebie** [comment]
at that time more or less apear the exchange between ES - MA that was programing before and have been never appear (I fond this project one month ago), maybe something was change from ESIOS.

**Comment by systemcatch** [comment]
When I run the ES-IB parser (and ES-CN) I get the following;
```bash
(EM-env) chris@ThinkPad:~/electricitymap$ python -m parsers.ES_IB
Traceback (most recent call last):
  File "/home/chris/EM-env/lib/python3.5/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/chris/EM-env/lib/python3.5/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/home/chris/EM-env/lib/python3.5/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/home/chris/EM-env/lib/python3.5/site-packages/urllib3/connection.py", line 326, in connect
    ssl_context=context)
  File "/home/chris/EM-env/lib/python3.5/site-packages/urllib3/util/ssl_.py", line 329, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.5/ssl.py", line 377, in wrap_socket
    _context=self)
  File "/usr/lib/python3.5/ssl.py", line 752, in __init__
    self.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 988, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 633, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/chris/EM-env/lib/python3.5/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/home/chris/EM-env/lib/python3.5/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/chris/EM-env/lib/python3.5/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='demanda.ree.es', port=443): Max retries exceeded with url: /WSvisionaMovilesBalearesRest/resources/demandaGeneracionBaleares?curva=BALEARES&fecha=2018-05-19 (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/chris/electricitymap/parsers/ES_IB.py", line 106, in <module>
    print(fetch_consumption('ES-IB', session))
  File "/home/chris/electricitymap/parsers/ES_IB.py", line 16, in fetch_consumption
    responses = BalearicIslands(ses).get_all()
  File "/home/chris/EM-env/lib/python3.5/site-packages/ree/balearicislands.py", line 13, in get_all
    return self.get(None, False)
  File "/home/chris/EM-env/lib/python3.5/site-packages/ree/balearicislands.py", line 10, in get
    return super(self.__class__, self).get("BALEARES", "Europe/Madrid", "Baleares", date, last)
  File "/home/chris/EM-env/lib/python3.5/site-packages/ree/core/scraper.py", line 23, in get
    for value in self._request(url):
  File "/home/chris/EM-env/lib/python3.5/site-packages/ree/core/scraper.py", line 72, in _request
    response = self.session.request("GET", url)
  File "/home/chris/EM-env/lib/python3.5/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/chris/EM-env/lib/python3.5/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/chris/EM-env/lib/python3.5/site-packages/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='demanda.ree.es', port=443): Max retries exceeded with url: /WSvisionaMovilesBalearesRest/resources/demandaGeneracionBaleares?curva=BALEARES&fecha=2018-05-19 (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)'),))

```
This points to their SSL configuration being wrong, firefox will still load the site but an analysis of the certificate shows many issues.

![ree_ssl](https://user-images.githubusercontent.com/30196510/40270839-16ad42e6-5b8c-11e8-9a4b-2d60a1116bd9.png)

There are 3 possible fixes for this:

- Set verify=False in ree (bad practice, quick fix).
- Manually add their certificate to EM trust store and point to that when verifying.
- Get the site to fix their configuration.
