### ISSUE TITLE
GB-NIR urls have changed

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#1474]
```
Traceback (most recent call last):
  File "/home/feeder/lib/fetch_data.py", line 130, in launch_parsers
    **parser_kwargs)
  File "/home/electricitymap/parsers/GB_NIR.py", line 258, in fetch_production
    thermal_df = create_thermal_df(thermal_data)
  File "/home/electricitymap/parsers/GB_NIR.py", line 95, in create_thermal_df
    usecols=cols_to_use)
  File "/usr/local/lib/python3.6/site-packages/pandas/io/parsers.py", line 709, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.6/site-packages/pandas/io/parsers.py", line 449, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/lib/python3.6/site-packages/pandas/io/parsers.py", line 818, in __init__
    self._make_engine(self.engine)
  File "/usr/local/lib/python3.6/site-packages/pandas/io/parsers.py", line 1049, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/usr/local/lib/python3.6/site-packages/pandas/io/parsers.py", line 1747, in __init__
    raise ValueError("Usecols do not match names.")
ValueError: Usecols do not match names.
```

**Comment by systemcatch** [comment]
Something has changed on the site which results in not getting the excel data properly.  Time for more fun with aspx pages!

**Comment by lorrieq** [comment]
It looks like at least the values sent for `btnDownloadCSV` and `_ig_def_dp_cal_clientState` have changed from what the parser sends but I must be missing something as I didn't manage to get it working when I was looking a few days ago.

**Comment by systemcatch** [comment]
The urls have changed very slightly e.g.

http://www.soni.ltd.uk/DownloadCentre/aspx/FuelMix.aspx
has become
http://ws.soni.ltd.uk/DownloadCentre/aspx/FuelMix.aspx
