### ISSUE TITLE
DO bug

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#1475]
```
Traceback (most recent call last):
  File "/home/feeder/lib/fetch_data.py", line 130, in launch_parsers
    **parser_kwargs)
  File "/home/electricitymap/parsers/DO.py", line 313, in fetch_production
    dat = data_formatter(get_data(session=None))
  File "/home/electricitymap/parsers/DO.py", line 99, in get_data
    rows = tbs.find_all("td")
AttributeError: 'NoneType' object has no attribute 'find_all'
```

**Comment by lorrieq** [comment]
This looks to be working fine again. I can run locally and there is data on the map.

**Comment by corradio** [comment]
ok - closing then.
