### ISSUE TITLE
US-IPC is occasionally missing a key

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#1478]
```
Traceback (most recent call last):
  File "/home/feeder/lib/fetch_data.py", line 130, in launch_parsers
    **parser_kwargs)
  File "/home/electricitymap/parsers/US_IPC.py", line 129, in fetch_production
    processed_data = data_processer(raw_data, logger)
  File "/home/electricitymap/parsers/US_IPC.py", line 83, in data_processer
    production.pop(key)
KeyError: 'Net Purchases'
```

**Comment by systemcatch** [comment]
Sometimes the 'Net Purchases' key is missing so a keyerror is raised by the pop function.  Supplying a default None argument fixes this.
