### ISSUE TITLE
SV bug

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#1479]
```
Traceback (most recent call last):
  File "/home/feeder/lib/fetch_data.py", line 130, in launch_parsers
    **parser_kwargs)
  File "/home/electricitymap/parsers/SV.py", line 167, in fetch_production
    parsed = data_parser(req)
  File "/home/electricitymap/parsers/SV.py", line 94, in data_parser
    j = json.loads(item[0])
  File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by jarek** [comment]
This stack trace means that the response from the server was blank (empty string) where you were expecting JSON. That's probably fine to leave as an error like this, trying to catch JSON decode errors and give useful error messages would be quite labour intensive.

**Comment by corradio** [comment]
ok I just raised the issue without really looking into it. Feel free to
close if you believe it's an outlier

**Comment by systemcatch** [comment]
El Salvador is fine for the past 24 hours so I'll close this since it's not recurring.
