### ISSUE TITLE
IN-PB ValueError: month must be 1..12

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#854]
Seen right now:

Traceback (most recent call last):
  File "feeder.py", line 136, in fetch_consumption
    objs = parser(country_code, session)
  File "/home/feeder/lib_electricitymap/parsers/IN_PB.py", line 89, in fetch_consumption
    india_date = date_time_strings_to_kolkata_date(date_text, "MM/DD/YYYY", time_text, "HH:mm:ss")
  File "/home/feeder/lib_electricitymap/parsers/IN_PB.py", line 24, in date_time_strings_to_kolkata_date
    return get(date_time, date_format)
  File "/usr/local/lib/python2.7/site-packages/arrow/api.py", line 23, in get
    return _factory.get(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/arrow/factory.py", line 198, in get
    dt = parser.DateTimeParser(locale).parse(args[0], args[1])
  File "/usr/local/lib/python2.7/site-packages/arrow/parser.py", line 167, in parse
    return self._build_datetime(parts)
  File "/usr/local/lib/python2.7/site-packages/arrow/parser.py", line 253, in _build_datetime
    tzinfo=parts.get('tzinfo'))
ValueError: month must be in 1..12

**Comment by systemcatch** [comment]
@blackleg had a fix for this but it was rejected. This error was seen 3574 times in the past 90 days according to the logger.

**Comment by corradio** [comment]
Yeah this error is very annoying. It seems like their formatting is not consistent.
I don't have a good solution for this. Ideas?

**Comment by blackleg** [comment]
@corradio You could use temporary the [closed pull request](https://github.com/tmrowco/electricitymap/pull/862), it isn't the best solution but it works.

**Comment by systemcatch** [comment]
Using the closed pull request is probably the quickest way. We could also use something like dateutil's parser instead of arrow's get() which is known to be quite lax when parsing.

**Comment by systemcatch** [comment]
Does the format change at a certain point (e.g. halfway through the month) or is it just switching randomly?

@blackleg I think you should resubmit the pull request and we will give it a try. At least the production mix doesn't suffer from the same problem.
