### ISSUE TITLE
Docker-compose fails on webpack --bail

### ISSUE THREAD

**Issue by emilmahler** [tmrowco/electricitymap#871]
Running `sudo docker-compose run --rm web npm run watch` fails on webpack --bail.

Here is the output:
ModuleNotFoundError: Module not found: Error: Cannot resolve module 'child_process' in /home/node_modules/xmlhttprequest/lib
    at /home/node_modules/webpack/lib/Compilation.js:229:38
    at onDoneResolving (/home/node_modules/webpack/lib/NormalModuleFactory.js:29:20)
    at /home/node_modules/webpack/lib/NormalModuleFactory.js:85:20
    at /home/node_modules/webpack/node_modules/async/lib/async.js:726:13
    at /home/node_modules/webpack/node_modules/async/lib/async.js:52:16
    at done (/home/node_modules/webpack/node_modules/async/lib/async.js:241:17)
    at /home/node_modules/webpack/node_modules/async/lib/async.js:44:16
    at /home/node_modules/webpack/node_modules/async/lib/async.js:723:17
    at /home/node_modules/webpack/node_modules/async/lib/async.js:167:37
    at /home/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:24:19
    at onResolved (/home/node_modules/enhanced-resolve/lib/Resolver.js:38:18)
    at innerCallback (/home/node_modules/enhanced-resolve/lib/Resolver.js:94:11)
    at loggingCallbackWrapper (/home/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
    at /home/node_modules/tapable/lib/Tapable.js:134:6
    at /home/node_modules/enhanced-resolve/lib/ModulesInDirectoriesPlugin.js:54:23
    at /home/node_modules/enhanced-resolve/lib/Resolver.js:191:15
    at /home/node_modules/enhanced-resolve/lib/ModulesInDirectoriesPlugin.js:45:26
    at loggingCallbackWrapper (/home/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
    at /home/node_modules/tapable/lib/Tapable.js:134:6
    at /home/node_modules/enhanced-resolve/lib/Resolver.js:122:33
    at /home/node_modules/enhanced-resolve/lib/Resolver.js:191:15
    at applyPluginsParallelBailResult.createInnerCallback.log (/home/node_modules/enhanced-resolve/lib/Resolver.js:110:4)
    at loggingCallbackWrapper (/home/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
    at /home/node_modules/tapable/lib/Tapable.js:134:6
    at Tapable.<anonymous> (/home/node_modules/enhanced-resolve/lib/FileAppendPlugin.js:31:26)
    at /home/node_modules/enhanced-resolve/lib/Resolver.js:191:15
    at /home/node_modules/enhanced-resolve/lib/FileAppendPlugin.js:28:12
    at Storage.finished (/home/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /home/node_modules/graceful-fs/polyfills.js:284:29
    at FSReqWrap.oncomplete (fs.js:123:15)
resolve module child_process in /home/node_modules/xmlhttprequest/lib
  looking for modules in /home/node_modules
    /home/node_modules/child_process doesn't exist (module as directory)
    resolve 'file' child_process in /home/node_modules
      resolve file
        /home/node_modules/child_process doesn't exist
        /home/node_modules/child_process.webpack.js doesn't exist
        /home/node_modules/child_process.web.js doesn't exist
        /home/node_modules/child_process.js doesn't exist
        /home/node_modules/child_process.json doesn't exist

npm info lifecycle electricitymap-api@0.0.1~build: Failed to exec build script
npm ERR! Linux 4.9.0-4-amd64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! electricitymap-api@0.0.1 build: `webpack --bail`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electricitymap-api@0.0.1 build script 'webpack --bail'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electricitymap-api package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack --bail
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electricitymap-api
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electricitymap-api
npm ERR! There is likely additional logging output above.

My system:
Linux 4.9.0-4-amd64 #1 SMP Debian 4.9.51-1 (2017-09-28) x86_64 GNU/Linux

**Comment by corradio** [comment]
Hum - do you run with docker? It's the recommended way.
Else, I think you might in better luck trying to update your node, npm and webpack versions.

Olivier

**Comment by emilmahler** [comment]
It's via 'sudo docker-compose run --rm web npm run watch' (so Docker!) on a clean GCE Debian VM.

**Comment by corradio** [comment]
Can you try `docker-compose build web --no-cache` to force a fresh rebuild
first?

**Comment by emilmahler** [comment]
It gets stuck on webpack --bail again when running `docker-compose build web --no-cache`

**Comment by corradio** [comment]
Actually the proper command is `docker-compose build --no-cache web`.
Just did here and it works. By the way, did you pull the latest version of
the master branch?

Olivier

**Comment by corradio** [comment]
Closing this due to inactivity. Feel free to re-open if needed
