### ISSUE TITLE
Stattnet exchange parser issue for EE -> FI

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#939]
feeder_1  | Exception while fetching exchange of EE->FI
feeder_1  | Traceback (most recent call last):
feeder_1  |   File "feeder.py", line 187, in fetch_exchange
feeder_1  |     objs = parser(country_code1, country_code2, session)
feeder_1  |   File "/home/feeder/lib_electricitymap/parsers/statnett.py", line 144, in fetch_exchange
feeder_1  |     exchanges_mapping[sorted_exchange]))
feeder_1  |   File "/home/feeder/lib_electricitymap/parsers/statnett.py", line 143, in <lambda>
feeder_1  |     data = _sum_of_exchanges(map(lambda e: _fetch_exchanges_from_sorted_bidding_zones(e, r),
feeder_1  |   File "/home/feeder/lib_electricitymap/parsers/statnett.py", line 130, in _fetch_exchanges_from_sorted_bidding_zones
feeder_1  |     return fetch_exchange_by_bidding_zone(zones[0], zones[1], session)
feeder_1  | IndexError: list index out of range

**Comment by corradio** [comment]
@brunolajoie can you take a look at this one ? We're not collecting data anymore for EE -> FI
