### ISSUE TITLE
Bolivia data handling needs to be improved

### ISSUE THREAD

**Issue by systemcatch** [tmrowco/electricitymap#984]
Looks like there is sometimes an extra key present which is missing from the mapping dict.  This causes the parser to fail constantly.  We need to add this key to the mapping then setup error handling so that any new keys raise warnings in the logger rather causing total failure.

Good first issue for someone looking to get involved.
```
chris@ThinkPad:~/electricitymap/parsers$ python3 BO.py 
fetch_production() ->
Traceback (most recent call last):
  File "BO.py", line 155, in <module>
    print(fetch_production())
  File "BO.py", line 103, in fetch_production
    data_temp = fetch_hourly_production(country_code, obj, h, formatted_date)
  File "BO.py", line 68, in fetch_hourly_production
    data['production'][i_type] = obj[MAP_GENERATION[i_type]][obj.hour == hour].iloc[0]
  File "/usr/local/lib/python3.4/dist-packages/pandas/core/frame.py", line 2139, in __getitem__
    return self._getitem_column(key)
  File "/usr/local/lib/python3.4/dist-packages/pandas/core/frame.py", line 2146, in _getitem_column
    return self._get_item_cache(key)
  File "/usr/local/lib/python3.4/dist-packages/pandas/core/generic.py", line 1842, in _get_item_cache
    values = self._data.get(item)
  File "/usr/local/lib/python3.4/dist-packages/pandas/core/internals.py", line 3843, in get
    loc = self.items.get_loc(item)
  File "/usr/local/lib/python3.4/dist-packages/pandas/core/indexes/base.py", line 2527, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 117, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 139, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1265, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1273, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Intermitentes'
```

**Comment by systemcatch** [comment]
So this isn't due to a Key missing.  When there is no generation for Intermitentes (wind) instead of zero a null tag is used which is odd but since this data is passed to flash later maybe there's a reason?  Anyway we will need to deal with this somehow to stop regular data loss.

The parser could do with some general refactoring but probably safer to put tests in place first.

**Comment by systemcatch** [comment]
KeyError should be fixed now. However the way data is handled by this parser can be significantly improved, currently it makes a dataframe for each hour but this is the same one each time as it just requests the daily data page.
